//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNongSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATHANG
    {
        public int MAGH { get; set; }
        public int MANV { get; set; }
        public int MAKH { get; set; }
        public int MATT { get; set; }
        public int MAVANCHUYEN { get; set; }
        public string MAVOUCHER { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
    
        public virtual GIOHANG GIOHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual THANHTOAN THANHTOAN { get; set; }
        public virtual VANCHUYEN VANCHUYEN { get; set; }
        public virtual VOUCHER VOUCHER { get; set; }
    }
}
