//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNongSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.GIOHANGs = new HashSet<GIOHANG>();
            this.NHANVIENs = new HashSet<NHANVIEN>();
        }
    
        public int MA_SP { get; set; }
        public string TEN_SP { get; set; }
        public Nullable<double> GIABAN { get; set; }
        public Nullable<double> GIAGOC { get; set; }
        public string VANCHUYEN { get; set; }
        public string THONGTINSP { get; set; }
        public string THUONGHIEU { get; set; }
        public Nullable<double> GIAMGIA { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string IMAGES { get; set; }
        public Nullable<int> MALOAISP { get; set; }
    
        public virtual DANHMUCSANPHAM DANHMUCSANPHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
    }
}
