//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WebNongSan.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TAIKHOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOAN()
        {
            this.DATHANGs = new HashSet<DATHANG>();
            this.KHACHHANGs = new HashSet<KHACHHANG>();
        }
    
        public int MAKH { get; set; }
        [Required(ErrorMessage ="Nhap Day Du Thong Tin")]
        public string TENKH { get; set; }
        [Required(ErrorMessage = "Nhap Day Du Thong Tin")]
        [DataType(DataType.EmailAddress,ErrorMessage ="Nhap dung dia chi email")]
        public string EMAIL { get; set; }
        public int SDT { get; set; }
        [Required(ErrorMessage = "Nhap Day Du Thong Tin")]
        [DataType(DataType.Password)]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$",ErrorMessage ="Mat khau tu 8 - 15 kí tự bao gồm chữ hoa,thường và sô")]
        public string MK { get; set; }
        [Required(ErrorMessage = "Nhap Day Du Thong Tin")]
        [DataType(DataType.Password)]
        [Compare("MK")]
        public string XACNHANMATKHAU { get; set; }
        public string MAXACTHUC { get; set; }
        public string  DangNhapThatBai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATHANG> DATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
    }
}
