//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNongSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKAdmin
    {
        public int MAadmin { get; set; }
        public string TENadmin { get; set; }
        public string EMAIL { get; set; }
        public int SDT { get; set; }
        public string MK { get; set; }
        public string XACNHANMATKHAU { get; set; }
        public string MAXACTHUC { get; set; }
        public string DangNhapThatBai;
    }
}
