//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNongSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIOHANG()
        {
            this.DATHANGs = new HashSet<DATHANG>();
        }
    
        public int MAGH { get; set; }
        public Nullable<int> MA_THIT { get; set; }
        public Nullable<int> MA_RAU { get; set; }
        public Nullable<int> MA_DOUONG { get; set; }
        public Nullable<int> MA_BANHKEO { get; set; }
        public Nullable<int> MA_SUA { get; set; }
    
        public virtual BANHKEO_DACSAN BANHKEO_DACSAN { get; set; }
        public virtual DOUONG_NUOCEP DOUONG_NUOCEP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATHANG> DATHANGs { get; set; }
        public virtual RAU_CU_TRAICAY RAU_CU_TRAICAY { get; set; }
        public virtual THIT_HAISAN_TRUNG THIT_HAISAN_TRUNG { get; set; }
    }
}
