//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNongSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public int MAKH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string GIOITINH { get; set; }
        public string DIACHICUTHE { get; set; }
        public string IMAGES { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
