//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNongSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUA_SANPHAMTUSUA
    {
        public int MA_SUA { get; set; }
        public string TEN_SUA { get; set; }
        public decimal GIABAN { get; set; }
        public Nullable<decimal> GIAGOC { get; set; }
        public string VANCHUYEN { get; set; }
        public string THONGTINSP { get; set; }
        public string THUONGHIEU { get; set; }
        public Nullable<int> GIAMGIA { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string IMAGES { get; set; }
    }
}
